import type { MesState } from '../mes/types';
import { seedReferenceTime } from './common';

const now = seedReferenceTime;

export const mesSeed: MesState = {
  routings: [
    {
      id: 'routing-router',
      itemId: 'item-fin-001',
      operations: [
        { opId: 'ROUTER-ASM', seq: 10, wcId: 'wc-assembly', stdTimeMin: 45 },
        { opId: 'ROUTER-TEST', seq: 20, wcId: 'wc-test', stdTimeMin: 35 },
        { opId: 'ROUTER-PACK', seq: 30, wcId: 'wc-pack', stdTimeMin: 12 },
      ],
    },
    {
      id: 'routing-flight-control',
      itemId: 'item-fin-002',
      operations: [
        { opId: 'FC-ASM', seq: 10, wcId: 'wc-assembly', stdTimeMin: 55 },
        { opId: 'FC-CAL', seq: 20, wcId: 'wc-calibration', stdTimeMin: 25 },
        { opId: 'FC-HIL', seq: 30, wcId: 'wc-hil', stdTimeMin: 45 },
        { opId: 'FC-BURN', seq: 40, wcId: 'wc-burnin', stdTimeMin: 60 },
      ],
    },
  ],
  workCenters: [
    { id: 'wc-assembly', name: 'Assembly Line 1', capabilityTags: ['smt', 'fpga'] },
    { id: 'wc-test', name: 'Functional Test Cell', capabilityTags: ['boundary-scan'] },
    { id: 'wc-pack', name: 'Packing Cell', capabilityTags: ['labeling', 'packout'] },
    { id: 'wc-calibration', name: 'Calibration Rig', capabilityTags: ['avionics', 'calibration'] },
    { id: 'wc-hil', name: 'HIL Validation Lab', capabilityTags: ['flight-control', 'hil'] },
    { id: 'wc-burnin', name: 'Burn-in Chamber', capabilityTags: ['thermal', 'stress'] },
  ],
  productionOrders: [
    {
      id: 'po-router-10',
      itemId: 'item-fin-001',
      qty: 25,
      dueDate: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 5).toISOString(),
      status: 'in-progress',
      releasedAt: new Date(now.getTime() - 1000 * 60 * 60 * 12).toISOString(),
    },
    {
      id: 'po-router-11',
      itemId: 'item-fin-001',
      qty: 15,
      dueDate: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 10).toISOString(),
      status: 'released',
      releasedAt: new Date(now.getTime() - 1000 * 60 * 60 * 3).toISOString(),
    },
    {
      id: 'po-flight-01',
      itemId: 'item-fin-002',
      qty: 12,
      dueDate: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 8).toISOString(),
      status: 'released',
      releasedAt: new Date(now.getTime() - 1000 * 60 * 60 * 6).toISOString(),
    },
  ],
  workOrders: [
    {
      id: 'wo-router-10-1',
      prodOrderId: 'po-router-10',
      opId: 'ROUTER-ASM',
      wcId: 'wc-assembly',
      assignee: 'alexei',
      status: 'in-progress',
      startedAt: new Date(now.getTime() - 1000 * 60 * 40).toISOString(),
    },
    {
      id: 'wo-router-10-2',
      prodOrderId: 'po-router-10',
      opId: 'ROUTER-TEST',
      wcId: 'wc-test',
      assignee: 'mila',
      status: 'planned',
    },
    {
      id: 'wo-router-11-1',
      prodOrderId: 'po-router-11',
      opId: 'ROUTER-ASM',
      wcId: 'wc-assembly',
      status: 'planned',
    },
    {
      id: 'wo-flight-01-1',
      prodOrderId: 'po-flight-01',
      opId: 'FC-ASM',
      wcId: 'wc-assembly',
      assignee: 'sergey',
      status: 'in-progress',
      startedAt: new Date(now.getTime() - 1000 * 60 * 90).toISOString(),
    },
    {
      id: 'wo-flight-01-2',
      prodOrderId: 'po-flight-01',
      opId: 'FC-CAL',
      wcId: 'wc-calibration',
      assignee: 'daria',
      status: 'planned',
    },
    {
      id: 'wo-flight-01-3',
      prodOrderId: 'po-flight-01',
      opId: 'FC-HIL',
      wcId: 'wc-hil',
      status: 'planned',
    },
    {
      id: 'wo-flight-01-4',
      prodOrderId: 'po-flight-01',
      opId: 'FC-BURN',
      wcId: 'wc-burnin',
      status: 'planned',
    },
  ],
  qualityChecks: [
    {
      id: 'qc-wo-router-10-1',
      entityType: 'WorkOrder',
      entityId: 'wo-router-10-1',
      ruleId: 'qc-solder-visual',
      status: 'pending',
      evidence: [],
    },
    {
      id: 'qc-flight-imu',
      entityType: 'WorkOrder',
      entityId: 'wo-flight-01-2',
      ruleId: 'qc-calibration',
      status: 'pending',
      evidence: [],
    },
    {
      id: 'qc-flight-hil',
      entityType: 'WorkOrder',
      entityId: 'wo-flight-01-3',
      ruleId: 'qc-hil-regression',
      status: 'blocked',
      evidence: [],
    },
  ],
  nonconformances: [
    {
      id: 'nc-router-01',
      refType: 'WorkOrder',
      refId: 'wo-router-10-1',
      severity: 'medium',
      status: 'investigating',
      action: 'Rework solder joint on board 4',
    },
    {
      id: 'nc-flight-01',
      refType: 'WorkOrder',
      refId: 'wo-flight-01-3',
      severity: 'high',
      status: 'open',
      action: 'Firmware regression blocked HIL campaign',
    },
    {
      id: 'nc-flash-045',
      refType: 'FlashJob',
      refId: 'flashjob-idrac-045',
      severity: 'medium',
      status: 'draft',
      action: 'Ошибка прошивки iDRAC 7.11.0, требуется анализ лога',
    },
  ],
  maintenanceOrders: [
    {
      id: 'mo-line1-01',
      assetId: 'wc-assembly',
      type: 'preventive',
      status: 'scheduled',
      schedule: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 2).toISOString(),
      logs: [
        {
          id: 'mo-line1-01-log1',
          ts: new Date(now.getTime() - 1000 * 60 * 60 * 24).toISOString(),
          note: 'Lubricated conveyor chain',
          actor: 'maintenance-bot',
        },
      ],
    },
    {
      id: 'mo-hil-02',
      assetId: 'wc-hil',
      type: 'corrective',
      status: 'in-progress',
      schedule: new Date(now.getTime() + 1000 * 60 * 60 * 6).toISOString(),
      logs: [
        {
          id: 'mo-hil-02-log1',
          ts: new Date(now.getTime() - 1000 * 60 * 45).toISOString(),
          note: 'Investigating actuator jitter during HIL run',
          actor: 'maintenance-bot',
        },
      ],
    },
  ],
  productionLines: [
    {
      id: 'pl-router-a',
      name: 'Router Assembly A',
      streamId: 'stream-network',
      workCenterIds: ['wc-assembly', 'wc-test', 'wc-pack'],
      shiftPattern: '2x8',
      taktTimeSec: 420,
      targetPerShift: 12,
      currentWip: 18,
      throughputPerShift: 10,
      availability: 0.92,
      blockers: ['Awaiting lot CAP-2404'],
    },
    {
      id: 'pl-router-b',
      name: 'Router Assembly B',
      streamId: 'stream-network',
      workCenterIds: ['wc-assembly', 'wc-test', 'wc-pack'],
      shiftPattern: 'night flex',
      taktTimeSec: 480,
      targetPerShift: 9,
      currentWip: 11,
      throughputPerShift: 8,
      availability: 0.87,
      blockers: [],
    },
    {
      id: 'pl-flight',
      name: 'Flight Control Line',
      streamId: 'stream-flight-control',
      workCenterIds: ['wc-assembly', 'wc-calibration', 'wc-hil', 'wc-burnin'],
      shiftPattern: '3x8',
      taktTimeSec: 1680,
      targetPerShift: 6,
      currentWip: 14,
      throughputPerShift: 5,
      availability: 0.78,
      blockers: ['Firmware 2.4.8 sign-off pending'],
    },
  ],
  valueStreams: [
    {
      id: 'stream-network',
      name: 'Network Infrastructure',
      focus: 'Edge routers & network appliances',
      demandThisWeek: 34,
      backlogUnits: 19,
      riskLevel: 'medium',
      gatekeepers: ['network-production'],
      nextMilestone: 'Customer FAT with CityNet on Friday',
    },
    {
      id: 'stream-flight-control',
      name: 'Flight Control Electronics',
      focus: 'Autopilot & flight control boards',
      demandThisWeek: 18,
      backlogUnits: 12,
      riskLevel: 'high',
      gatekeepers: ['flight-control-lab'],
      nextMilestone: 'Qualification run with avionics QA',
    },
  ],
  testCells: [
    {
      id: 'tc-hil-01',
      name: 'HIL Rig 01',
      capability: '6-axis motion simulation',
      status: 'online',
      queueDepth: 3,
      activePlanId: 'plan-flight-hil',
      shift: 'Day A',
      operators: ['daria', 'ilya'],
    },
    {
      id: 'tc-hil-02',
      name: 'HIL Rig 02',
      capability: 'Rotorcraft dynamics',
      status: 'maintenance',
      queueDepth: 5,
      activePlanId: 'plan-flight-hil',
      shift: 'Day B',
      operators: ['sergey'],
    },
    {
      id: 'tc-burn-01',
      name: 'Thermal Burn-In Chamber',
      capability: 'Environmental stress',
      status: 'online',
      queueDepth: 2,
      activePlanId: 'plan-burnin',
      shift: 'Swing',
      operators: ['valentina'],
    },
  ],
  testPlans: [
    {
      id: 'plan-flight-hil',
      name: 'Flight Control Regression',
      coverage: 0.93,
      cycleTimeMin: 45,
      ownerTeam: 'flight-control-lab',
      requiredFor: ['item-fin-002'],
      lastValidatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 20).toISOString(),
    },
    {
      id: 'plan-burnin',
      name: '48h Burn-in',
      coverage: 0.75,
      cycleTimeMin: 120,
      ownerTeam: 'environmental-test',
      requiredFor: ['item-fin-001', 'item-fin-002'],
      lastValidatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 72).toISOString(),
    },
  ],
  testRuns: [
    {
      id: 'run-hil-001',
      testCellId: 'tc-hil-01',
      planId: 'plan-flight-hil',
      boardSerial: 'FCB-2403-011',
      status: 'running',
      startedAt: new Date(now.getTime() - 1000 * 60 * 20).toISOString(),
      operatorId: 'daria',
      defectsFound: 0,
    },
    {
      id: 'run-hil-002',
      testCellId: 'tc-hil-01',
      planId: 'plan-flight-hil',
      boardSerial: 'FCB-2403-010',
      status: 'failed',
      startedAt: new Date(now.getTime() - 1000 * 60 * 90).toISOString(),
      finishedAt: new Date(now.getTime() - 1000 * 60 * 40).toISOString(),
      operatorId: 'ilya',
      defectsFound: 2,
    },
    {
      id: 'run-burn-001',
      testCellId: 'tc-burn-01',
      planId: 'plan-burnin',
      boardSerial: 'ER1U-24-1011',
      status: 'queued',
      startedAt: new Date(now.getTime() - 1000 * 60 * 10).toISOString(),
      operatorId: 'valentina',
      defectsFound: 0,
    },
  ],
  flashAgents: [
    {
      id: 'agent-ws-01',
      workstationId: 'ws-lab-01',
      workstationName: 'Станция прошивки · HIL 01',
      status: 'online',
      version: '1.4.3',
      ipAddress: '10.12.4.21',
      supportedTools: ['dfu-util', 'stm32flash', 'esptool', 'nrfutil'],
      lastSeenAt: new Date(now.getTime() - 1000 * 5).toISOString(),
      connectedPorts: ['ttyACM0', 'ttyUSB0', 'ttyUSB1'],
    },
    {
      id: 'agent-rack-02',
      workstationId: 'rack-burn-02',
      workstationName: 'Burn-in Рак 02',
      status: 'online',
      version: '1.3.9',
      ipAddress: '10.12.4.36',
      supportedTools: ['ipmitool', 'idrac-cli'],
      lastSeenAt: new Date(now.getTime() - 1000 * 45).toISOString(),
      connectedPorts: ['ttyUSB2'],
    },
    {
      id: 'agent-lab-offline',
      workstationId: 'ws-lab-02',
      workstationName: 'Станция прошивки · ESC 02',
      status: 'offline',
      version: '1.3.4',
      ipAddress: '10.12.4.22',
      supportedTools: ['esptool'],
      lastSeenAt: new Date(now.getTime() - 1000 * 60 * 40).toISOString(),
      connectedPorts: [],
    },
  ],
  flashPorts: [
    {
      id: 'ttyACM0',
      path: '/dev/ttyACM0',
      displayName: 'USB-C #1',
      vendorId: '0483',
      productId: 'df11',
      deviceHint: 'STM32 DFU (FC v2)',
      busy: true,
      state: 'flashing',
      workstationId: 'ws-lab-01',
      lastSeenAt: new Date(now.getTime() - 1000 * 2).toISOString(),
      notes: 'Контроль PID перед выдачей',
    },
    {
      id: 'ttyUSB0',
      path: '/dev/ttyUSB0',
      displayName: 'USB-C #2',
      vendorId: '0483',
      productId: '5740',
      deviceHint: 'Bootloader (ESC)',
      busy: false,
      state: 'ready',
      workstationId: 'ws-lab-01',
      lastSeenAt: new Date(now.getTime() - 1000 * 12).toISOString(),
    },
    {
      id: 'ttyUSB1',
      path: '/dev/ttyUSB1',
      displayName: 'USART #1',
      vendorId: '10C4',
      productId: 'EA60',
      deviceHint: 'Flight Controller Console',
      busy: false,
      state: 'bootloader',
      workstationId: 'ws-lab-01',
      lastSeenAt: new Date(now.getTime() - 1000 * 8).toISOString(),
    },
    {
      id: 'ttyUSB2',
      path: '/dev/ttyUSB2',
      displayName: 'Rack USB #4',
      vendorId: '413c',
      productId: 'a102',
      deviceHint: 'iDRAC console',
      busy: false,
      state: 'ok',
      workstationId: 'rack-burn-02',
      lastSeenAt: new Date(now.getTime() - 1000 * 60 * 3).toISOString(),
      notes: 'Последняя прошивка успешна',
    },
  ],
  flashArtifacts: [
    {
      id: 'artifact-fc-248',
      project: 'drones',
      deviceType: 'FC',
      model: 'QAV250-FC',
      version: 'v2.4.8',
      buildId: 'fc-248-2025-02-01',
      checksum: 'a8c5-24ff-90b1',
      url: 'https://artifacts.example.com/fc/v2.4.8.bin',
      releasedAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 3).toISOString(),
      allowed: true,
      compatibleModels: ['QAV250-FC', 'QAV300-FC'],
      mandatoryOptions: ['erase', 'verify'],
    },
    {
      id: 'artifact-esc-30a-v3',
      project: 'drones',
      deviceType: 'ESC',
      model: 'ESC-30A-V3',
      version: '3.0.2',
      buildId: 'esc-30a-v3-302',
      checksum: 'ff12-33aa-9900',
      url: 'https://artifacts.example.com/esc/v3.0.2.hex',
      releasedAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 10).toISOString(),
      allowed: true,
      compatibleModels: ['ESC-30A-V3'],
    },
    {
      id: 'artifact-idrac-7110',
      project: 'servers',
      deviceType: 'server',
      model: 'PowerEdge R640',
      version: 'iDRAC 7.11.0',
      buildId: 'idrac-7.11.0',
      checksum: '9c44-77aa-1bcf',
      url: 'https://artifacts.example.com/idrac/7.11.0.img',
      releasedAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 30).toISOString(),
      allowed: false,
      compatibleModels: ['PowerEdge R640', 'PowerEdge R740'],
    },
    {
      id: 'artifact-fc-249-rc1',
      project: 'drones',
      deviceType: 'FC',
      model: 'QAV250-FC',
      version: 'v2.4.9-rc1',
      buildId: 'fc-249-rc1',
      checksum: 'bb10-55de-abc1',
      url: 'https://artifacts.example.com/fc/v2.4.9-rc1.bin',
      releasedAt: new Date(now.getTime() - 1000 * 60 * 60 * 24).toISOString(),
      allowed: false,
      compatibleModels: ['QAV250-FC'],
      mandatoryOptions: ['erase'],
    },
  ],
  flashPresets: [
    {
      id: 'preset-fc-prod-248',
      name: 'FC-QAV250-Prod v2.4.8',
      project: 'drones',
      deviceType: 'FC',
      model: 'QAV250-FC',
      artifactId: 'artifact-fc-248',
      defaultOptions: {
        erase: true,
        verify: true,
        setParams: true,
        notes: 'Прописать PID и failsafe',
      },
      defaultChecklist: [
        { id: 'dfu', label: 'Войти в DFU-режим', required: true },
        { id: 'boot', label: 'Замкнуть BOOT0 перемычку', required: true },
        { id: 'power', label: 'Подключить питание стенда', required: true },
      ],
    },
    {
      id: 'preset-esc-30a',
      name: 'ESC-30A-V3 (BLHeli_S)',
      project: 'drones',
      deviceType: 'ESC',
      model: 'ESC-30A-V3',
      artifactId: 'artifact-esc-30a-v3',
      defaultOptions: {
        erase: true,
        verify: true,
        setParams: false,
        notes: 'Проверить направление вращения',
      },
      defaultChecklist: [
        { id: 'power', label: 'Подключить силовую шину', required: true },
        { id: 'signal', label: 'Подключить сигнальный провод к адаптеру', required: true },
      ],
    },
    {
      id: 'preset-idrac-7110',
      name: 'BIOS iDRAC 7.11.0',
      project: 'servers',
      deviceType: 'server',
      model: 'PowerEdge R640',
      artifactId: 'artifact-idrac-7110',
      defaultOptions: {
        erase: false,
        verify: true,
        setParams: true,
        notes: 'После прошивки выполнить power-cycle',
      },
      defaultChecklist: [
        { id: 'idrac', label: 'Перевести сервер в режим обслуживания', required: true },
        { id: 'network', label: 'Проверить сетевое подключение iDRAC', required: true },
      ],
      requiresMasterOverride: true,
    },
  ],
  flashJobs: [
    {
      id: 'flashjob-fc-001',
      jobNumber: 'FJ-20250205-001',
      portId: 'ttyACM0',
      workstationId: 'ws-lab-01',
      operator: 'technician-anna',
      status: 'running',
      project: 'drones',
      deviceType: 'FC',
      model: 'QAV250-FC',
      serialNumber: 'FC-24-00152',
      presetId: 'preset-fc-prod-248',
      artifactId: 'artifact-fc-248',
      artifactVersion: 'v2.4.8',
      checksum: 'a8c5-24ff-90b1',
      startedAt: new Date(now.getTime() - 1000 * 60 * 4).toISOString(),
      bytesWritten: 524288,
      speedKbps: 880,
      progressPercent: 37,
      etaSec: 280,
      log: [
        {
          id: 'log-fc-1',
          ts: new Date(now.getTime() - 1000 * 60 * 4).toISOString(),
          level: 'info',
          message: 'Подключение к dfu-util',
        },
        {
          id: 'log-fc-2',
          ts: new Date(now.getTime() - 1000 * 60 * 3.5).toISOString(),
          level: 'info',
          message: 'Начат erase всего образа',
        },
        {
          id: 'log-fc-3',
          ts: new Date(now.getTime() - 1000 * 60 * 3).toISOString(),
          level: 'info',
          message: 'Запись блока 128/256',
        },
      ],
      powerChecklist: [
        { id: 'dfu', label: 'Войти в DFU-режим', required: true },
        { id: 'boot', label: 'Замкнуть BOOT0 перемычку', required: true },
        { id: 'power', label: 'Подключить питание стенда', required: true },
      ],
    },
    {
      id: 'flashjob-esc-117',
      jobNumber: 'FJ-20250205-117',
      portId: 'ttyUSB0',
      workstationId: 'ws-lab-01',
      operator: 'technician-ivan',
      status: 'ok',
      project: 'drones',
      deviceType: 'ESC',
      model: 'ESC-30A-V3',
      serialNumber: 'ESC-30A-24-2201',
      presetId: 'preset-esc-30a',
      artifactId: 'artifact-esc-30a-v3',
      artifactVersion: '3.0.2',
      checksum: 'ff12-33aa-9900',
      startedAt: new Date(now.getTime() - 1000 * 60 * 25).toISOString(),
      finishedAt: new Date(now.getTime() - 1000 * 60 * 21).toISOString(),
      durationSec: 240,
      bytesWritten: 262144,
      speedKbps: 620,
      log: [
        {
          id: 'log-esc-1',
          ts: new Date(now.getTime() - 1000 * 60 * 25).toISOString(),
          level: 'info',
          message: 'Ожидание загрузчика BLHeli_S',
        },
        {
          id: 'log-esc-2',
          ts: new Date(now.getTime() - 1000 * 60 * 23).toISOString(),
          level: 'info',
          message: 'Верификация успешна',
        },
      ],
      resultLogUrl: 'https://mes.local/logs/FJ-20250205-117.txt',
      powerChecklist: [
        { id: 'power', label: 'Подключить силовую шину', required: true },
        { id: 'signal', label: 'Подключить сигнальный провод к адаптеру', required: true },
      ],
    },
    {
      id: 'flashjob-idrac-045',
      jobNumber: 'FJ-20250205-045',
      portId: 'ttyUSB2',
      workstationId: 'rack-burn-02',
      operator: 'tech-maria',
      status: 'error',
      project: 'servers',
      deviceType: 'server',
      model: 'PowerEdge R640',
      serialNumber: 'SRV-R640-19A03',
      presetId: 'preset-idrac-7110',
      artifactId: 'artifact-idrac-7110',
      artifactVersion: 'iDRAC 7.11.0',
      checksum: '9c44-77aa-1bcf',
      startedAt: new Date(now.getTime() - 1000 * 60 * 70).toISOString(),
      finishedAt: new Date(now.getTime() - 1000 * 60 * 64).toISOString(),
      durationSec: 360,
      bytesWritten: 44040192,
      speedKbps: 12000,
      log: [
        {
          id: 'log-idrac-1',
          ts: new Date(now.getTime() - 1000 * 60 * 70).toISOString(),
          level: 'info',
          message: 'Старт прошивки iDRAC по сети',
        },
        {
          id: 'log-idrac-2',
          ts: new Date(now.getTime() - 1000 * 60 * 66).toISOString(),
          level: 'warn',
          message: 'Контрольная сумма не совпала, повтор',
        },
        {
          id: 'log-idrac-3',
          ts: new Date(now.getTime() - 1000 * 60 * 65).toISOString(),
          level: 'error',
          message: 'Устройство вернуло код 74',
        },
      ],
      resultLogUrl: 'https://mes.local/logs/FJ-20250205-045.txt',
      ncrId: 'nc-flash-045',
      reflash: true,
      powerChecklist: [
        { id: 'idrac', label: 'Перевести сервер в режим обслуживания', required: true },
        { id: 'network', label: 'Проверить сетевое подключение iDRAC', required: true },
      ],
    },
  ],
  deviceSessions: [
    {
      serialNumber: 'FC-24-00152',
      project: 'drones',
      deviceType: 'FC',
      model: 'QAV250-FC',
      lastArtifactId: 'artifact-fc-248',
      lastArtifactVersion: 'v2.4.8',
      lastFlashedAt: new Date(now.getTime() - 1000 * 60 * 60 * 5).toISOString(),
      lastOperator: 'technician-anna',
      allowedArtifactIds: ['artifact-fc-248'],
      notes: 'PID калиброваны 2025-02-04',
    },
    {
      serialNumber: 'ESC-30A-24-2201',
      project: 'drones',
      deviceType: 'ESC',
      model: 'ESC-30A-V3',
      lastArtifactId: 'artifact-esc-30a-v3',
      lastArtifactVersion: '3.0.2',
      lastFlashedAt: new Date(now.getTime() - 1000 * 60 * 60 * 26).toISOString(),
      lastOperator: 'technician-ivan',
      allowedArtifactIds: ['artifact-esc-30a-v3'],
    },
    {
      serialNumber: 'SRV-R640-19A03',
      project: 'servers',
      deviceType: 'server',
      model: 'PowerEdge R640',
      lastArtifactId: 'artifact-idrac-7110',
      lastArtifactVersion: 'iDRAC 7.11.0',
      lastFlashedAt: new Date(now.getTime() - 1000 * 60 * 60 * 72).toISOString(),
      lastOperator: 'tech-maria',
      allowedArtifactIds: ['artifact-idrac-7110'],
      notes: 'Требуется проверка целостности после NCR',
    },
  ],
};
