import type { PassportTemplateLayout, ProductPassportState } from '../product-passport/types';
import { seedReferenceTime } from './common';

const now = seedReferenceTime;


const ciscoTemplateFields = [
  {
    id: 'tpl-field-role',
    key: 'role',
    label: 'Роль устройства',
    type: 'text' as const,
    required: true,
    defaultValue: 'Distribution switch',
  },
  {
    id: 'tpl-field-install-date',
    key: 'installDate',
    label: 'Дата ввода в эксплуатацию',
    type: 'date' as const,
    required: true,
  },
  {
    id: 'tpl-field-firmware',
    key: 'firmware',
    label: 'Текущая версия прошивки',
    type: 'text' as const,
    required: true,
    defaultValue: '17.12.4',
  },
  {
    id: 'tpl-field-power',
    key: 'powerProfile',
    label: 'Профиль питания',
    type: 'select' as const,
    options: [
      { label: 'AC (2 блока)', value: 'ac_dual' },
      { label: 'DC', value: 'dc' },
      { label: 'PoE+', value: 'poe_plus' },
    ],
    required: true,
  },
  {
    id: 'tpl-field-notes',
    key: 'notes',
    label: 'Примечания',
    type: 'multiline' as const,
  },
];

const dellTemplateFields = [
  {
    id: 'tpl-dell-os',
    key: 'osVersion',
    label: 'Операционная система',
    type: 'text' as const,
    required: true,
    defaultValue: 'ESXi 8.0',
  },
  {
    id: 'tpl-dell-cpu',
    key: 'cpuModel',
    label: 'Модель CPU',
    type: 'text' as const,
    required: true,
    defaultValue: 'Intel Xeon Gold 6430',
  },
  {
    id: 'tpl-dell-ram',
    key: 'ramGb',
    label: 'ОЗУ (ГБ)',
    type: 'number' as const,
    required: true,
    defaultValue: 256,
  },
  {
    id: 'tpl-dell-hypervisor',
    key: 'hypervisorCluster',
    label: 'Кластер гипервизора',
    type: 'text' as const,
  },
];

const vegmanTemplateFields = [
  {
    id: 'vegman-product-name',
    key: 'productName',
    label: 'Наименование изделия',
    type: 'text' as const,
    required: true,
  },
  {
    id: 'vegman-article',
    key: 'article',
    label: 'Артикул',
    type: 'text' as const,
    required: true,
  },
  {
    id: 'vegman-serial',
    key: 'serial',
    label: 'Серийный номер',
    type: 'text' as const,
    required: true,
  },
  {
    id: 'vegman-manufactured',
    key: 'manufacturedAt',
    label: 'Дата производства',
    type: 'date' as const,
    required: true,
  },
  {
    id: 'vegman-firmware',
    key: 'firmware',
    label: 'Версия прошивки',
    type: 'text' as const,
  },
  {
    id: 'vegman-inspector',
    key: 'inspector',
    label: 'Проверяющий',
    type: 'text' as const,
  },
  {
    id: 'vegman-location',
    key: 'location',
    label: 'Расположение',
    type: 'text' as const,
  },
  {
    id: 'vegman-ip-address',
    key: 'ipAddress',
    label: 'IP-адрес',
    type: 'text' as const,
  },
  {
    id: 'vegman-responsible',
    key: 'responsible',
    label: 'Ответственный',
    type: 'text' as const,
  },
  {
    id: 'vegman-notes',
    key: 'notes',
    label: 'Примечания',
    type: 'multiline' as const,
  },
  {
    id: 'vegman-components',
    key: 'components',
    label: 'Комплектующие',
    type: 'table' as const,
    minRows: 0,
    maxRows: 50,
    columns: [
      { id: 'vegman-components-name', key: 'name', title: 'Наименование', type: 'text' as const },
      { id: 'vegman-components-pn', key: 'pn', title: 'Part Number', type: 'text' as const },
      { id: 'vegman-components-qty', key: 'qty', title: 'Кол-во', type: 'number' as const },
      { id: 'vegman-components-remark', key: 'remark', title: 'Примечание', type: 'text' as const },
    ],
  },
];

const vegmanTemplateLayout: PassportTemplateLayout = {
  sheetName: 'Документ',
  columnWidths: { 2: 20, 3: 45, 4: 30, 5: 15 },
  rowHeights: { 2: 28, 13: 20, 14: 20, 15: 20, 18: 20 },
  staticCells: [
    {
      id: 'vegman-title',
      row: 2,
      col: 2,
      value: 'ПАСПОРТ ИЗДЕЛИЯ',
      merge: { cols: 4 },
      style: {
        font: { name: 'Calibri', size: 16, bold: true },
        alignment: { horizontal: 'center', vertical: 'middle' },
      },
    },
    {
      id: 'vegman-subtitle',
      row: 4,
      col: 2,
      value: 'Модель:',
      style: {
        font: { name: 'Calibri', size: 11, bold: true },
        alignment: { horizontal: 'right', vertical: 'middle' },
      },
    },
    {
      id: 'vegman-model-value',
      row: 4,
      col: 3,
      value: 'S220',
      style: {
        font: { name: 'Calibri', size: 11 },
        alignment: { horizontal: 'left', vertical: 'middle' },
      },
    },
    {
      id: 'vegman-organization-label',
      row: 5,
      col: 2,
      value: 'Организация:',
      style: {
        font: { name: 'Calibri', size: 11, bold: true },
        alignment: { horizontal: 'right', vertical: 'middle' },
      },
    },
    {
      id: 'vegman-organization-value',
      row: 5,
      col: 3,
      value: '<наименование организации>',
      merge: { cols: 3 },
      style: {
        font: { name: 'Calibri', size: 11 },
        alignment: { horizontal: 'left', vertical: 'middle' },
      },
    },
    {
      id: 'vegman-product-label',
      row: 6,
      col: 2,
      value: 'Наименование:',
      style: {
        font: { name: 'Calibri', size: 11, bold: true },
        alignment: { horizontal: 'right', vertical: 'middle' },
      },
    },
    {
      id: 'vegman-article-label',
      row: 7,
      col: 2,
      value: 'Артикул:',
      style: {
        font: { name: 'Calibri', size: 11, bold: true },
        alignment: { horizontal: 'right', vertical: 'middle' },
      },
    },
    {
      id: 'vegman-serial-label',
      row: 8,
      col: 2,
      value: 'Серийный №:',
      style: {
        font: { name: 'Calibri', size: 11, bold: true },
        alignment: { horizontal: 'right', vertical: 'middle' },
      },
    },
    {
      id: 'vegman-date-label',
      row: 9,
      col: 2,
      value: 'Дата произв.:',
      style: {
        font: { name: 'Calibri', size: 11, bold: true },
        alignment: { horizontal: 'right', vertical: 'middle' },
      },
    },
    {
      id: 'vegman-firmware-label',
      row: 10,
      col: 2,
      value: 'Прошивка:',
      style: {
        font: { name: 'Calibri', size: 11, bold: true },
        alignment: { horizontal: 'right', vertical: 'middle' },
      },
    },
    {
      id: 'vegman-inspector-label',
      row: 11,
      col: 2,
      value: 'Проверил:',
      style: {
        font: { name: 'Calibri', size: 11, bold: true },
        alignment: { horizontal: 'right', vertical: 'middle' },
      },
    },
    {
      id: 'vegman-location-label',
      row: 12,
      col: 2,
      value: 'Расположение:',
      style: {
        font: { name: 'Calibri', size: 11, bold: true },
        alignment: { horizontal: 'right', vertical: 'middle' },
      },
    },
    {
      id: 'vegman-notes-label',
      row: 13,
      col: 2,
      value: 'Примечания:',
      style: {
        font: { name: 'Calibri', size: 11, bold: true },
        alignment: { horizontal: 'right', vertical: 'middle' },
      },
    },
    {
      id: 'vegman-ip-label',
      row: 16,
      col: 2,
      value: 'IP-адрес:',
      style: {
        font: { name: 'Calibri', size: 11, bold: true },
        alignment: { horizontal: 'right', vertical: 'middle' },
      },
    },
    {
      id: 'vegman-responsible-label',
      row: 17,
      col: 2,
      value: 'Ответственный:',
      style: {
        font: { name: 'Calibri', size: 11, bold: true },
        alignment: { horizontal: 'right', vertical: 'middle' },
      },
    },
    {
      id: 'vegman-qr-frame',
      row: 8,
      col: 5,
      value: '',
      merge: { rows: 4 },
      style: {
        border: {
          top: { style: 'thin' },
          bottom: { style: 'thin' },
          left: { style: 'thin' },
          right: { style: 'thin' },
        },
      },
    },
  ],
  bindings: [
    {
      fieldKey: 'productName',
      row: 6,
      col: 3,
      merge: { cols: 3 },
      style: {
        font: { name: 'Calibri', size: 11 },
        alignment: { horizontal: 'left', vertical: 'middle', wrapText: true },
      },
    },
    {
      fieldKey: 'article',
      row: 7,
      col: 3,
      merge: { cols: 2 },
      style: {
        font: { name: 'Calibri', size: 11 },
        alignment: { horizontal: 'left', vertical: 'middle' },
      },
    },
    {
      fieldKey: 'serial',
      row: 8,
      col: 3,
      merge: { cols: 2 },
      style: {
        font: { name: 'Calibri', size: 11 },
        alignment: { horizontal: 'left', vertical: 'middle' },
      },
    },
    {
      fieldKey: 'manufacturedAt',
      row: 9,
      col: 3,
      merge: { cols: 2 },
      style: {
        font: { name: 'Calibri', size: 11 },
        alignment: { horizontal: 'left', vertical: 'middle' },
        numberFormat: 'dd.mm.yyyy',
      },
    },
    {
      fieldKey: 'firmware',
      row: 10,
      col: 3,
      merge: { cols: 2 },
      style: {
        font: { name: 'Calibri', size: 11 },
        alignment: { horizontal: 'left', vertical: 'middle' },
      },
    },
    {
      fieldKey: 'inspector',
      row: 11,
      col: 3,
      merge: { cols: 3 },
      style: {
        font: { name: 'Calibri', size: 11 },
        alignment: { horizontal: 'left', vertical: 'middle' },
      },
    },
    {
      fieldKey: 'location',
      row: 12,
      col: 3,
      merge: { cols: 3 },
      style: {
        font: { name: 'Calibri', size: 11 },
        alignment: { horizontal: 'left', vertical: 'middle' },
      },
    },
    {
      fieldKey: 'notes',
      row: 13,
      col: 3,
      merge: { cols: 3, rows: 3 },
      style: {
        font: { name: 'Calibri', size: 11 },
        alignment: { horizontal: 'left', vertical: 'top', wrapText: true },
        border: {
          top: { style: 'thin' },
          bottom: { style: 'thin' },
          left: { style: 'thin' },
          right: { style: 'thin' },
        },
      },
    },
    {
      fieldKey: 'ipAddress',
      row: 16,
      col: 3,
      style: {
        font: { name: 'Calibri', size: 11 },
        alignment: { horizontal: 'left', vertical: 'middle' },
      },
    },
    {
      fieldKey: 'responsible',
      row: 17,
      col: 3,
      merge: { cols: 3 },
      style: {
        font: { name: 'Calibri', size: 11 },
        alignment: { horizontal: 'left', vertical: 'middle' },
      },
    },
  ],
  tables: [
    {
      fieldKey: 'components',
      row: 18,
      col: 2,
      drawHeader: true,
      showGrid: true,
      minRows: 0,
      maxRows: 50,
      fillEmptyRowsWithGrid: true,
      columns: [
        {
          id: 'vegman-components-name-col',
          key: 'name',
          title: 'Наименование',
          type: 'text' as const,
          width: 30,
          style: {
            font: { name: 'Calibri', size: 11 },
            alignment: { horizontal: 'left', vertical: 'top', wrapText: true },
          },
          headerStyle: {
            font: { name: 'Calibri', size: 11, bold: true },
            alignment: { horizontal: 'center', vertical: 'middle' },
            border: {
              top: { style: 'thin' },
              bottom: { style: 'thin' },
              left: { style: 'thin' },
              right: { style: 'thin' },
            },
          },
        },
        {
          id: 'vegman-components-pn-col',
          key: 'pn',
          title: 'Part Number',
          type: 'text' as const,
          width: 20,
          style: {
            font: { name: 'Calibri', size: 11 },
            alignment: { horizontal: 'left', vertical: 'top', wrapText: true },
          },
          headerStyle: {
            font: { name: 'Calibri', size: 11, bold: true },
            alignment: { horizontal: 'center', vertical: 'middle' },
            border: {
              top: { style: 'thin' },
              bottom: { style: 'thin' },
              left: { style: 'thin' },
              right: { style: 'thin' },
            },
          },
        },
        {
          id: 'vegman-components-qty-col',
          key: 'qty',
          title: 'Кол-во',
          type: 'number' as const,
          width: 8,
          style: {
            font: { name: 'Calibri', size: 11 },
            alignment: { horizontal: 'center', vertical: 'middle' },
            numberFormat: '0',
          },
          headerStyle: {
            font: { name: 'Calibri', size: 11, bold: true },
            alignment: { horizontal: 'center', vertical: 'middle' },
            border: {
              top: { style: 'thin' },
              bottom: { style: 'thin' },
              left: { style: 'thin' },
              right: { style: 'thin' },
            },
          },
        },
        {
          id: 'vegman-components-note-col',
          key: 'remark',
          title: 'Примечание',
          type: 'text' as const,
          width: 30,
          style: {
            font: { name: 'Calibri', size: 11 },
            alignment: { horizontal: 'left', vertical: 'top', wrapText: true },
          },
          headerStyle: {
            font: { name: 'Calibri', size: 11, bold: true },
            alignment: { horizontal: 'center', vertical: 'middle' },
            border: {
              top: { style: 'thin' },
              bottom: { style: 'thin' },
              left: { style: 'thin' },
              right: { style: 'thin' },
            },
          },
        },
      ],
      headerStyle: {
        font: { name: 'Calibri', size: 11, bold: true },
        alignment: { horizontal: 'center', vertical: 'middle' },
      },
      rowStyle: {
        font: { name: 'Calibri', size: 11 },
        alignment: { horizontal: 'left', vertical: 'top', wrapText: true },
      },
      gridStyle: { style: 'thin', color: '#000000' },
    },
  ],
} as const;

export const passportsSeed: ProductPassportState = {
  devices: [
    {
      id: 'device-ast-1001',
      assetTag: 'AST-1001',
      deviceModelId: 'model-cisco-c9500',
      serialNumber: 'SN123456789',
      ipAddress: '10.10.10.5',
      location: 'DC-West / Стойка 42',
      owner: 'Команда сетей',
      status: 'in_service',
    },
    {
      id: 'device-ast-1042',
      assetTag: 'AST-1042',
      deviceModelId: 'model-dell-r650',
      serialNumber: 'R650-2404-1042',
      ipAddress: '10.20.2.15',
      location: 'DC-East / Подрядчик зона 3',
      owner: 'Команда виртуализации',
      status: 'maintenance',
    },
    {
      id: 'device-ast-1100',
      assetTag: 'AST-1100',
      deviceModelId: 'model-juniper-srx',
      serialNumber: 'SRX-1100-99',
      ipAddress: '172.16.5.1',
      location: 'DC-West / Пограничный сегмент',
      owner: 'Команда безопасности',
      status: 'in_service',
    },
    {
      id: 'device-vegman-220-01',
      assetTag: 'VG-220-01',
      deviceModelId: 'model-vegman-s220',
      serialNumber: 'S220-VEGMAN-0001',
      ipAddress: '10.55.0.20',
      location: 'Цех 2 / Линия Vegman',
      owner: 'Команда производственной автоматики',
      status: 'in_service',
    },
  ],
  deviceModels: [
    {
      id: 'model-cisco-c9500',
      vendor: 'Cisco',
      name: 'Cisco Catalyst 9500',
      description: 'Модульное ядро сети корпоративного датацентра.',
    },
    {
      id: 'model-dell-r650',
      vendor: 'Dell',
      name: 'Dell PowerEdge R650',
      description: 'Высокоплотный сервер виртуализации.',
    },
    {
      id: 'model-juniper-srx',
      vendor: 'Juniper',
      name: 'Juniper SRX340',
      description: 'Пограничный межсетевой экран и VPN-шлюз.',
    },
    {
      id: 'model-vegman-s220',
      vendor: 'Vegman',
      name: 'S220',
      description: 'Компактный терминал Vegman S220 для индустриальных IoT-сценариев.',
    },
  ],
  templates: [
    {
      id: 'tpl-cisco-base-v1',
      deviceModelId: 'model-cisco-c9500',
      name: 'Cisco C9500 — базовый паспорт',
      description: 'Рекомендуемый комплект полей для паспорта ядрового коммутатора.',
      version: 1,
      isActive: true,
      createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 30).toISOString(),
      fields: ciscoTemplateFields.map(field => ({ ...field })),
      status: 'published',
    },
    {
      id: 'tpl-dell-base-v1',
      deviceModelId: 'model-dell-r650',
      name: 'Dell R650 — стандарт',
      description: 'Основные сведения для серверов виртуализации.',
      version: 1,
      isActive: true,
      createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 45).toISOString(),
      fields: dellTemplateFields.map(field => ({ ...field })),
      status: 'published',
    },
    {
      id: 'tpl-vegman-s220-v1',
      deviceModelId: 'model-vegman-s220',
      name: 'Vegman S220 — паспорт изделия',
      description: 'Эталонный паспорт Vegman S220 с таблицей комплектующих.',
      version: 1,
      isActive: true,
      createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 7).toISOString(),
      fields: vegmanTemplateFields.map(field => ({ ...field })),
      layout: vegmanTemplateLayout,
      status: 'published',
      fileNamePattern: 'Паспорт_S220_{serial}',
    },
  ],
  passports: [
    {
      id: 'passport-ast-1001-v1',
      deviceId: 'device-ast-1001',
      templateId: 'tpl-cisco-base-v1',
      status: 'ready',
      version: 1,
      createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 28).toISOString(),
      updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 2).toISOString(),
      metadata: {
        assetTag: 'AST-1001',
        modelName: 'Cisco Catalyst 9500',
        vendor: 'Cisco',
        serialNumber: 'SN123456789',
        ipAddress: '10.10.10.5',
        location: 'DC-West / Стойка 42',
        owner: 'Команда сетей',
      },
      schema: ciscoTemplateFields.map(field => ({ ...field })),
      fieldValues: {
        role: 'Distribution switch',
        installDate: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 365).toISOString().slice(0, 10),
        firmware: '17.12.4',
        powerProfile: 'ac_dual',
        notes: 'Паспорт сформирован автоматически после модернизации ядра.',
      },
      attachments: [
        {
          id: 'attachment-ast-1001-acceptance',
          name: 'Акт ввода в эксплуатацию.pdf',
          url: '/static/demo/router-datasheet.pdf',
          uploadedAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 27).toISOString(),
        },
      ],
      history: [
        {
          ts: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 28).toISOString(),
          action: 'draft',
          details: 'Черновик создан на основе активного шаблона.',
          actor: 'dev-admin',
        },
        {
          ts: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 2).toISOString(),
          action: 'finalize',
          details: 'Паспорт утверждён техническим директором.',
          actor: 'cto-office',
        },
      ],
    },
  ],
  deviceHistory: {
    'device-ast-1001': [
      {
        id: 'hist-ast-1001-1',
        deviceId: 'device-ast-1001',
        ts: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 400).toISOString(),
        action: 'Получено на склад',
        details: 'Принято по заказу PO-4587 в количестве 1 шт.',
        actor: 'Складской отдел',
      },
      {
        id: 'hist-ast-1001-2',
        deviceId: 'device-ast-1001',
        ts: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 365).toISOString(),
        action: 'Ввод в эксплуатацию',
        details: 'Установлено в стойку 42, порт uplink — DC-CORE-01.',
        actor: 'Команда сетей',
      },
      {
        id: 'hist-ast-1001-3',
        deviceId: 'device-ast-1001',
        ts: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 14).toISOString(),
        action: 'Обслуживание',
        details: 'Заменён вентилятор FAN2 после предупреждения датчика.',
        actor: 'Сервисный центр',
      },
    ],
    'device-ast-1042': [
      {
        id: 'hist-ast-1042-1',
        deviceId: 'device-ast-1042',
        ts: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 90).toISOString(),
        action: 'Перемещение',
        details: 'Отправлено в зону подрядчика для планового апгрейда.',
        actor: 'Команда виртуализации',
      },
    ],
    'device-ast-1100': [
      {
        id: 'hist-ast-1100-1',
        deviceId: 'device-ast-1100',
        ts: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 120).toISOString(),
        action: 'Тестирование',
        details: 'Пройдено нагрузочное тестирование IPS.',
        actor: 'SOC',
      },
      {
        id: 'hist-ast-1100-2',
        deviceId: 'device-ast-1100',
        ts: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 3).toISOString(),
        action: 'Инцидент',
        details: 'Зафиксирован всплеск CPU при анализе DDoS, включена защита.',
        actor: 'SOC',
      },
    ],
  },
};
