import type { WorkforceState } from '../workforce/types';
import { seedReferenceTime } from './common';

const now = seedReferenceTime;

export const workforceSeed: WorkforceState = {
  teams: [
    {
      id: 'team-network',
      name: 'Сборка сетевых устройств',
      scope: 'Edge routers и сетевые контроллеры',
      accessScopes: ['network-production'],
      headcount: 24,
      location: 'Цех 1 / Линия A',
      shiftModel: '2x8 + поддержка выходных',
    },
    {
      id: 'team-flight',
      name: 'Лаборатория flight control',
      scope: 'Платы автопилота, HIL и калибровка',
      accessScopes: ['flight-control-lab'],
      headcount: 12,
      location: 'HIL Lab / Clean room',
      shiftModel: '3 смены по 8 часов',
    },
    {
      id: 'team-quality',
      name: 'Качество и соответствие',
      scope: 'IPC аудит, FA и сертификация',
      accessScopes: ['qa-office'],
      headcount: 9,
      location: 'Quality Hub / Офис 2.18',
      shiftModel: 'Гибридная 5/2',
    },
    {
      id: 'team-maintenance',
      name: 'Инженеры обслуживания',
      scope: 'Простои, TPM и обеспечение смен',
      accessScopes: ['maintenance-core'],
      headcount: 6,
      location: 'Сервисный центр',
      shiftModel: 'Дежурства 12/24',
    },
  ],
  members: [
    {
      id: 'member-alexei',
      name: 'Алексей Иванов',
      teamId: 'team-network',
      title: 'Старший оператор SMT',
      skills: ['SMT', 'IPC-A-610', 'line-balance'],
      shift: 'Day A',
      productivityScore: 0.88,
      utilization: 0.82,
      currentLoadHours: 6.5,
      badges: ['Наставник смены'],
    },
    {
      id: 'member-mila',
      name: 'Мила Ким',
      teamId: 'team-network',
      title: 'Техник функционального теста',
      skills: ['boundary-scan', 'reporting'],
      shift: 'Swing',
      productivityScore: 0.79,
      utilization: 0.7,
      currentLoadHours: 5.1,
      badges: ['Kaizen lead'],
    },
    {
      id: 'member-daria',
      name: 'Дарья Петрова',
      teamId: 'team-flight',
      title: 'Инженер HIL стендов',
      skills: ['HIL', 'MATLAB', 'safety-case'],
      shift: 'Night',
      productivityScore: 0.91,
      utilization: 0.86,
      currentLoadHours: 7.4,
      badges: ['Root-cause expert'],
    },
    {
      id: 'member-sergey',
      name: 'Сергей Афанасьев',
      teamId: 'team-flight',
      title: 'Инженер по калибровке',
      skills: ['calibration', 'labview'],
      shift: 'Day B',
      productivityScore: 0.76,
      utilization: 0.64,
      currentLoadHours: 4.2,
      badges: ['Cross-trained'],
    },
    {
      id: 'member-irina',
      name: 'Ирина Соколова',
      teamId: 'team-quality',
      title: 'Специалист по качеству',
      skills: ['8D', 'PPAP', 'audit'],
      shift: 'Day',
      productivityScore: 0.83,
      utilization: 0.71,
      currentLoadHours: 3.8,
      badges: ['Lead auditor'],
    },
    {
      id: 'member-anton',
      name: 'Антон Власов',
      teamId: 'team-maintenance',
      title: 'Инженер TPM',
      skills: ['TPM', 'electro-mech'],
      shift: 'On-call',
      productivityScore: 0.74,
      utilization: 0.6,
      currentLoadHours: 2.5,
      badges: ['CMMS curator'],
    },
  ],
  assignments: [
    {
      id: 'assign-wo-router-10-1',
      memberId: 'member-alexei',
      entityType: 'WorkOrder',
      entityId: 'wo-router-10-1',
      status: 'active',
      effortHours: 6,
      startedAt: new Date(now.getTime() - 1000 * 60 * 40).toISOString(),
    },
    {
      id: 'assign-wo-router-10-2',
      memberId: 'member-mila',
      entityType: 'WorkOrder',
      entityId: 'wo-router-10-2',
      status: 'planned',
      effortHours: 4,
      dueAt: new Date(now.getTime() + 1000 * 60 * 120).toISOString(),
    },
    {
      id: 'assign-hil-001',
      memberId: 'member-daria',
      entityType: 'TestRun',
      entityId: 'run-hil-001',
      status: 'active',
      effortHours: 1.5,
      startedAt: new Date(now.getTime() - 1000 * 60 * 20).toISOString(),
    },
    {
      id: 'assign-calibration',
      memberId: 'member-sergey',
      entityType: 'WorkOrder',
      entityId: 'wo-flight-01-2',
      status: 'planned',
      effortHours: 5,
      dueAt: new Date(now.getTime() + 1000 * 60 * 60 * 8).toISOString(),
    },
    {
      id: 'assign-quality-report',
      memberId: 'member-irina',
      entityType: 'Task',
      entityId: 'task-003',
      status: 'active',
      effortHours: 3,
      startedAt: new Date(now.getTime() - 1000 * 60 * 90).toISOString(),
    },
    {
      id: 'assign-maintenance',
      memberId: 'member-anton',
      entityType: 'WorkOrder',
      entityId: 'mo-hil-02',
      status: 'active',
      effortHours: 2,
      startedAt: new Date(now.getTime() - 1000 * 60 * 50).toISOString(),
    },
  ],
  utilization: [
    {
      id: 'util-network',
      teamId: 'team-network',
      weekStart: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 3).toISOString(),
      actual: 0.84,
      target: 0.8,
      overtimeHours: 4,
    },
    {
      id: 'util-flight',
      teamId: 'team-flight',
      weekStart: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 3).toISOString(),
      actual: 0.73,
      target: 0.78,
      overtimeHours: 6,
    },
    {
      id: 'util-quality',
      teamId: 'team-quality',
      weekStart: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 3).toISOString(),
      actual: 0.68,
      target: 0.7,
      overtimeHours: 1,
    },
  ],
  performance: [
    {
      memberId: 'member-alexei',
      completedThisWeek: 42,
      avgCycleTimeMin: 11,
      firstPassYield: 0.97,
      labourEfficiency: 0.91,
    },
    {
      memberId: 'member-daria',
      completedThisWeek: 8,
      avgCycleTimeMin: 47,
      firstPassYield: 0.88,
      labourEfficiency: 0.87,
    },
    {
      memberId: 'member-irina',
      completedThisWeek: 5,
      avgCycleTimeMin: 35,
      firstPassYield: 0.99,
      labourEfficiency: 0.82,
    },
    {
      memberId: 'member-anton',
      completedThisWeek: 9,
      avgCycleTimeMin: 62,
      firstPassYield: 0.92,
      labourEfficiency: 0.78,
    },
  ],
  reports: [
    {
      id: 'report-weekly',
      label: 'Еженедельный отчёт по производству',
      generatedAt: new Date(now.getTime() - 1000 * 60 * 15).toISOString(),
      ownerTeam: 'operations-office',
      highlights: [
        '10% рост выпуска по сети благодаря снижению переналадок',
        'HIL линия ожидает релиз прошивки 2.4.8 для завершения цикла',
      ],
    },
    {
      id: 'report-flight',
      label: 'Отчёт по Flight Control',
      generatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 6).toISOString(),
      ownerTeam: 'flight-control-lab',
      highlights: [
        'Первый проход 88% — требуется повторная прогонка тест-плана',
        'Расписание смен скорректировано для покрытия ночного окна',
      ],
    },
  ],
};
